coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# EstimatorTest is used as test code by the unit tests. Exclude it from code coverage.
ignore:
  - "**/PennyLogger.EstimatorTest/**"
